<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.1

$CONF['sql_user']         = '';
$CONF['sql_passwd']       = '';
$CONF['sql_host']         = 'localhost';
$CONF['sql_db']           = '';
$CONF['ftp_use']          = '0';
$CONF['allow_dir_backup'] = '0';
$CONF['email_use']        = '0';
$CONF['sitename']         = 'mySite';
$CONF['lang']             = 'english';
$CONF['import_error']     = '1';
$CONF['no_login']         = '0';
$CONF['login']            = '0';
$CONF['dir_backup']       = '0';
$CONF['dir_rec']          = '1';
$CONF['email']            = '';
$CONF['ftp_pasv']         = '1';
$CONF['ftp_del']          = '1';
$CONF['ftp_server']       = 'example.net';
$CONF['ftp_user']         = '';
$CONF['ftp_passwd']       = '';
$CONF['ftp_path']         = 'example/';
$CONF['ftp_port']         = '21';
$CONF['date']             = '%x %X';
$CONF['del_time']         = '7';
$CONF['del_number']       = '5';
$CONF['timelimit']        = '60';
$CONF['confirm']          = '1';
$CONF['stylesheet']       = 'standard';
